fix: Disable caching on Dockerbuild
/usr/bin/docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --file ./build/Dockerfile --iidfile /home/runner/work/_temp/docker-actions-toolkit-ZI5wM0/build-iidfile-04e9fb5963.txt --tag localhost:5000/flanksource/config-db:latest --metadata-file /home/runner/work/_temp/docker-actions-toolkit-ZI5wM0/build-metadata-65477e26c9.json --push .
ERROR: failed to build: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-cache-backends/
Reference
Check build summary support
Error: buildx failed with: Learn more at https://docs.docker.com/go/build-cache-backends/